app/aplicacion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('', include('oposicion.urls')),
]

app/oposicion/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',views.homepage, name="homepage"),
    path('temario/',views.temario, name="temario"),
    path('temario/<int:id>/',views.mostrar_temario, name="mostrar_temario"),
    path('temario/<int:id>/<path:path>', views.ver_pdf, name='ver_pdf'),
    path('temario/eliminartemario/<int:id>/',views.eliminarTemario, name="eliminarTemario"),
    path('pruebas/',views.pruebas, name="pruebas"),
    path('pruebas/<int:id>/',views.mostrar_prueba, name="mostrar_prueba"),
    path('pruebas/eliminarprueba/<int:id>/',views.eliminarPrueba, name="eliminarPrueba"),
    path('pruebas/realizarprueba/<str:titulo>/',views.realizarPrueba, name="realizarPrueba"),
    path('progreso/',views.progreso, name="progreso"),
    path('progreso/<int:id>/',views.progresoOposicion, name="progresoOposicion"),
]

app/usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('sign/',views.sign, name="sign"),
    path('perfil/', views.perfil, name="perfil"),
    path('perfil/editar', views.editarPerfil, name="editarPerfil"),
    path('perfil/eliminar', views.eliminarPerfil, name="eliminarPerfil"),
    path('logout/', views.logout, name="logout"),


    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form2.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done2.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm2.html'), name='password_reset_confirm'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete2.html'), name='password_reset_complete'),
]

app/oposicion/models.py
from django.db import models
from usuarios.models import User
from django.core.validators import MinValueValidator

def path_usuario_temario(instance, filename):
    # instance.user es el usuario que sube el archivo
    return f'{instance.NomUsuario.username}/{filename}'

class Oposicion(models.Model):
    NomOposicion = models.CharField(null=False, max_length=100)
    OpoVisible = models.BooleanField(null=False, default=True)

    def __str__(self):
        return self.NomOposicion

    class Meta:
        db_table = "OPOSICION"


class Temario(models.Model):
    NomTemario = models.CharField(null=False, max_length=50)
    NumPaginas = models.DecimalField(null=False, max_digits=4, decimal_places=0)
    TemVisible = models.BooleanField(null=False, default=True)
    Archivo = models.FileField(upload_to=path_usuario_temario, null=False)
    NomUsuario = models.ForeignKey(User, on_delete=models.CASCADE)
    IdOposicion = models.ForeignKey(Oposicion, on_delete=models.CASCADE)

    def __str__(self):
        return self.NomTemario
    
    class Meta:
        db_table = "TEMARIO"
    
class Prueba(models.Model):
    NomPrueba = models.CharField(null=False, max_length=50)
    NumPreguntas = models.DecimalField(null=False, max_digits=2, decimal_places=0)
    PruVisible = models.BooleanField(null=False, default=True)

    def __str__(self):
        return self.NomPrueba
    
    class Meta:
        db_table = "PRUEBA"
    
class Progreso(models.Model):
    Nota = models.DecimalField(null=False, max_digits=4, decimal_places=2)
    PregAcertadas = models.DecimalField(null=False, max_digits=3, decimal_places=0)
    PregFalladas = models.DecimalField(null=False, max_digits=3, decimal_places=0)
    PregBlanco = models.DecimalField(null=False, max_digits=3, decimal_places=0)
    Tiempo = models.IntegerField(null=False, validators=[MinValueValidator(1)])
    IdPrueba = models.ForeignKey(Prueba, on_delete=models.CASCADE)

    class Meta:
        db_table = "PROGRESO" 

class Formado_por(models.Model):
    IdTemario = models.ForeignKey(Temario, on_delete=models.CASCADE)
    IdPrueba = models.ForeignKey(Prueba, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['IdTemario', 'IdPrueba'], name='pk_IdTemario_IdPrueba'
            )
        ]

        db_table = "FORMADO_POR"

app/oposicion/forms.py
from django import forms
from . models import Temario, Prueba, Formado_por

class TemarioForm(forms.ModelForm):
    
    class Meta:
        model = Temario
        fields = ['NomTemario','IdOposicion','Archivo']

class ExamenForm(forms.Form):
    def __init__(self, *args, **kwargs):
        preguntas = kwargs.pop('preguntas', None) 
        super(ExamenForm, self).__init__(*args, **kwargs)
  
        for pregunta in preguntas:
            opciones = [(opcion, opcion) for opcion in pregunta['opciones']]
            self.fields[f'pregunta_{pregunta["id"]}'] = forms.ChoiceField(label=pregunta['texto'], choices=opciones, widget=forms.RadioSelect(), required=False)

        
    def evaluar_respuestas(self, preguntas):
        puntaje = 0
        incorrectas = 0
        blanco = 0
        nota = 0
        acertadas = []
        falladas = []
        blancas = []
        respuestas = []
        respuestas_usuario = self.cleaned_data
        for pregunta in preguntas:
            nombre_campo = f'pregunta_{pregunta["id"]}'
            respuesta_usuario = respuestas_usuario.get(nombre_campo)
            respuestas.append((pregunta["id"],respuesta_usuario))
            if respuesta_usuario == pregunta['respuesta_correcta']:
                puntaje += 1
                nota += 1
                acertadas.append(pregunta["id"])
            elif  respuesta_usuario == '':
                blanco += 1
                blancas.append(pregunta["id"])
            else:
                incorrectas += 1
                nota -= 0.25
                falladas.append(pregunta["id"])

        if nota > 0:
            nota = (nota / (puntaje+blanco+incorrectas)) * 10
        else:
            nota = 0
            
        return puntaje, incorrectas, blanco, nota, acertadas, falladas, blancas, respuestas
    
class PruebaForm(forms.ModelForm):
    temarios = forms.ModelMultipleChoiceField(queryset=Temario.objects.all())
    class Meta:
        model = Prueba
        fields = ['NomPrueba', 'temarios','NumPreguntas']


    

app/oposicion/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from PyPDF2 import PdfFileReader
from oposicion.models import Temario, Oposicion, Formado_por, Prueba, Progreso
from . forms import TemarioForm, ExamenForm, PruebaForm
import json, os
from django.conf import settings
from django.db.models import Value, CharField, F
from django.db.models.functions import Concat
from django.http import FileResponse
from datetime import datetime
import decimal
from . import ia
from aplicacion.settings import MEDIA_ROOT

def homepage(request):
     if request.user.is_authenticated:
        return redirect('temario')
     else:
        return render(request, 'oposicion/index.html')

@login_required(login_url="sign")
def temario(request):
    nombreOposiciones = []
    user=request.user.username
    form = TemarioForm(request.POST, request.FILES)
    all_oposicion = Oposicion.objects.all().order_by('NomOposicion')
    all_temario = Temario.objects.all().prefetch_related('NomUsuario','IdOposicion').filter(NomUsuario__username=user,TemVisible=True).values_list('IdOposicion', flat=True).distinct()
    temarios = Temario.objects.all().filter(NomUsuario__username=user,TemVisible=True).values_list('NomTemario', 'IdOposicion_id')

    for temario in all_temario:
        oposicion = Oposicion.objects.get(id=temario)
        cantidad = Temario.objects.filter(NomUsuario__username=user,IdOposicion=temario,TemVisible=True).count()
        nombreOposiciones.append((oposicion.id, oposicion.NomOposicion, cantidad))

    if request.method == 'POST':
        NomTemario = request.POST.get('NomTemario')
        IdOposicion = int(request.POST.get('IdOposicion'))
        for nombre, id in temarios:
            if(NomTemario == nombre and id == IdOposicion):
                context=messages.add_message(request=request,level=messages.ERROR, message="Ya existe un fichero con el mismo nombre.")
                return render(request, 'oposicion/temario.html',{'nombreOposiciones':nombreOposiciones, 'all_oposicion':all_oposicion, 'form':form,'context':context})
            
        if request.FILES['Archivo'].name.endswith('.pdf'):
            pdf_file = request.FILES['Archivo']
            pdf_reader = PdfFileReader(pdf_file)
            num_paginas = pdf_reader.numPages
            if form.is_valid():
                temario = form.save(commit=False)
                temario.NumPaginas = num_paginas
                temario.NomUsuario = request.user
                temario.Archivo = request.FILES['Archivo']
                temario.save()
                return redirect('temario')
        else:
            context=messages.add_message(request=request,level=messages.ERROR, message="Solo se permiten subir archivos en formato pdf.")
            return render(request, 'oposicion/temario.html',{'nombreOposiciones':nombreOposiciones, 'all_oposicion':all_oposicion, 'form':form,'context':context})
            
    
    return render(request, 'oposicion/temario.html',{'nombreOposiciones':nombreOposiciones, 'all_oposicion':all_oposicion, 'form':form})


@login_required(login_url="sign")
def mostrar_temario(request, id):
    user=request.user.username
    oposicion = get_object_or_404(Oposicion, id=id)
    temarios = Temario.objects.filter(IdOposicion=id,NomUsuario=user,TemVisible=True)
    
    return render(request, 'oposicion/mostrar_temario.html', {'oposicion': oposicion,'temarios': temarios})

@login_required(login_url="sign")
def eliminarTemario(request, id):
    user=request.user.username
    usuario_temario = Temario.objects.all().filter(id=id).values_list('NomUsuario__username', flat=True).first()
    num_pruebas = Formado_por.objects.all().filter(IdTemario_id=id).count()
    archivo = Temario.objects.get(id=id)
    
    if user == usuario_temario and num_pruebas > 0:
        elemento = get_object_or_404(Temario, id=id)
        elemento.TemVisible = False
        elemento.save()
    else:
        file_path = os.path.join(settings.MEDIA_ROOT, archivo.Archivo.name)
        temario = Temario.objects.get(id=id)
        temario.delete()
        os.remove(file_path)

    return redirect ('temario')

@login_required(login_url="sign")
def pruebas(request):
    nombreOposiciones = []
    lista_url = []
    user=request.user.username
    form = PruebaForm(request.POST)

    all_pruebas = Formado_por.objects.prefetch_related('IdTemario','IdPrueba').filter(IdTemario__NomUsuario__username=user,IdPrueba__PruVisible=True).values_list('IdTemario__IdOposicion', flat=True).distinct()
    all_temario = Temario.objects.all().filter(NomUsuario=user, TemVisible=True).values_list('id','NomTemario','IdOposicion').order_by('IdOposicion')
    all_oposicion = Oposicion.objects.all().filter(id__in=[temario[2] for temario in all_temario]).order_by('NomOposicion')

    for pruebas in all_pruebas:
        oposicion = Oposicion.objects.get(id=pruebas)
        cantidad = Formado_por.objects.all().prefetch_related('IdTemario','IdPrueba').filter(IdTemario__IdOposicion=oposicion,IdTemario__NomUsuario__username=user,IdPrueba__PruVisible=True).values('IdPrueba').distinct().count()
        nombreOposiciones.append((oposicion.id, oposicion.NomOposicion, cantidad))
    

    if request.method == 'POST':
        if form.is_valid():
            oposicion = []
            NomPrueba = form.cleaned_data.get('NomPrueba')
            NumPreguntas = form.cleaned_data.get('NumPreguntas')
            temarios_seleccionados = form.cleaned_data['temarios']

            for temario in temarios_seleccionados:
                oposicion.append(temario.IdOposicion)
            
            if oposicion.count(oposicion[0]) == len(oposicion):
                for temario in temarios_seleccionados:
                    urls = Temario.objects.filter(id=temario.id).values_list('Archivo', flat=True)
                    for url in urls:
                        lista_url.append(MEDIA_ROOT + url)

                texto = ia.crear(lista_url,NumPreguntas,NomPrueba)

                user_folder_path = os.path.join(settings.STATICFILES_DIRS[1], 'oposicion', 'examenes', f'{user}')
                if not os.path.exists(user_folder_path):
                    os.makedirs(user_folder_path)
              
                json_file_path = os.path.join(settings.STATICFILES_DIRS[1], 'oposicion', 'examenes', f'{user}',f'{NomPrueba}.json')
                with open(json_file_path, 'w', encoding='utf-8') as json_file:
                    json_file.write(texto)
                
                with open(json_file_path, 'r', encoding='utf-8') as json_file:
                    data = json.load(json_file)

                    # Obtener la lista de preguntas
                    preguntas = data["examen"]["preguntas"]

                    # Obtener el último elemento de la lista de preguntas
                    ultima_pregunta = preguntas[-1]

                    # Obtener el valor del atributo "id" del último elemento
                    ultimo_id = ultima_pregunta["id"]
            
                prueba = form.save(commit=False)
                prueba.NumPreguntas = ultimo_id
                prueba.save()
                
                for temario in temarios_seleccionados:
                    Formado_por.objects.create(IdPrueba=prueba, IdTemario=temario)
                
                nueva_ruta = os.path.join(settings.STATICFILES_DIRS[1], 'oposicion', 'examenes', f'{user}', f'{prueba.NomPrueba}_{prueba.id}.json')
                os.rename(json_file_path, nueva_ruta)
                
            else:
                context=messages.add_message(request=request,level=messages.ERROR, message="El temario escogido tiene que ser de la misma oposición.")
                return render(request, 'oposicion/pruebas.html',{'all_oposicion':all_oposicion , 'all_temario':all_temario ,'all_pruebas':all_pruebas, 'nombreOposiciones':nombreOposiciones, 'form':form, 'context':context})

            
        return redirect('pruebas')
    
    return render(request, 'oposicion/pruebas.html',{'all_oposicion':all_oposicion , 'all_temario':all_temario ,'all_pruebas':all_pruebas, 'nombreOposiciones':nombreOposiciones, 'form':form})

@login_required(login_url="sign")
def mostrar_prueba(request, id):
    user=request.user.username
    oposicion = get_object_or_404(Oposicion, id=id)
    pruebas = Formado_por.objects.all().prefetch_related('IdTemario','IdPrueba').filter(IdTemario__IdOposicion=id,IdTemario__NomUsuario__username=user,IdPrueba__PruVisible=True).annotate(nombre_id=Concat(F('IdPrueba__NomPrueba'), Value('_'), F('IdPrueba__id'), output_field=CharField())).values_list('IdPrueba', 'IdPrueba__NomPrueba','nombre_id','IdPrueba__NumPreguntas').distinct()
    temario = Formado_por.objects.all().prefetch_related('IdTemario','IdPrueba').filter(IdTemario__IdOposicion=id,IdTemario__NomUsuario__username=user,IdPrueba__PruVisible=True).values_list('IdPrueba','IdTemario__NomTemario')
    return render(request, 'oposicion/mostrar_prueba.html', {'oposicion': oposicion,'pruebas': pruebas, 'temario':temario})

@login_required(login_url="sign")
def eliminarPrueba(request, id):
    user=request.user.username
    usuario_prueba = Formado_por.objects.all().prefetch_related('IdTemario','IdPrueba').filter(IdPrueba=id).values_list('IdTemario__NomUsuario__username', flat=True).first()
    num_progreso = Progreso.objects.all().filter(IdPrueba=id).count()
    prueba = Prueba.objects.get(id=id)
    json_file_path = os.path.join(settings.STATICFILES_DIRS[1], 'oposicion', 'examenes', f'{user}',f'{prueba.NomPrueba}_{prueba.id}.json')

    if user == usuario_prueba and num_progreso > 0:
        elemento = get_object_or_404(Prueba, id=id)
        elemento.PruVisible = False
        elemento.save()
    else:
        prueba.delete()
        os.remove(json_file_path)

    return redirect ('pruebas')
    

@login_required(login_url="sign")
def realizarPrueba(request, titulo):

app/oposicion/templates/oposicion/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TFG</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'oposicion/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <style>
      .select2-container {
        z-index: 999999 !important;
      }

    </style>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand titulo">TFG</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% block section1 %}
                {% endblock section1 %}
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {% if user.is_authenticated %}Hola, {{ user.username }}{% endif %}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'perfil' %}">Ver perfil</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

      <section>
        {% block section2 %}
        {% endblock section2 %}
      </section>


</body>

<script src="{% static 'oposicion/script.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-rc.0/js/select2.js" integrity="sha512-w8hm+E7eW80RcTpHGflcYz2A9wvvjbADCPcqepR11qvCUQmZEo65n7o+3JYpYP1yrzW6xyHqcqrNMOz1kQ+o6A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
  $(document).ready(function() {
      $('.select2').select2({
        maximumSelectionLength: 1 
      });
    });
</script>

<script>
  $(document).ready(function() {
      $('.select2-temario').select2();
    });
</script>

<script>
  $( document ).ready(function() {
  $('#myModal').modal('toggle')
});
</script>

</html>

app/oposicion/templates/oposicion/pruebas.html
{% extends 'oposicion/base.html' %}

{% block section1 %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'temario' %}">Temario</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page"  href="{% url 'pruebas' %}">Pruebas</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'progreso' %}">Progreso</a>
</li>
{% endblock section1 %}

{% block section2 %}
{% load static %}
<div class="container">
<div class="row breadcrumb">
  <div style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Pruebas</li>
    </ol>
  </div>
</div>
<div class="row bloque">
  {% if all_pruebas %}
  {% for id,NomOposicion,cantidad in nombreOposiciones %}
    <div class="card card-view" style="width: 18rem;">
      <a class="card-text enlaceTemario" href="{% url 'mostrar_prueba' id=id %}">
        <img src="{% static 'oposicion/img/fondoOposicion.jpg' %}" class="card-img-top" alt="">
        <div class="card-body">
          <p class="card-text enlaceTemario">{{NomOposicion}}</p>
          <p class="cantidad">{{cantidad}} prueba/s</p>
        </div>
      </a>
    </div>
    {% endfor %}
    {% else %}
    <p class="card-text">No hay pruebas creadas.</p>
  {% endif %}
</div>
</div>
<div class="contenedorBotonTemario">
  <button data-bs-toggle="modal" data-bs-target="#exampleModal" class="botonTemario">CREAR PRUEBA</button>
  {% if messages %}
  {% for message in messages %}
      <div class="mensaje">
          <small class="text-danger">{{ message }}</small>
      </div>
  {% endfor %}
  {% endif %}
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Crear prueba</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="POST" id="formtemario" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="modal-body">
          <div class="mb-3">
            <label for="id_NomPrueba" class="form-label">Título</label>
            <input type="text" class="form-control" name="NomPrueba" maxlength="50" required="" aria-invalid="true" id="id_NomPrueba">
          </div>
          <div class="mb-3">
            <label for="id_temarios" class="form-label">Temario</label>
            <select class="form-select select2-temario" name="temarios" required="" aria-invalid="true" id="id_temarios" multiple="" style="width: 100%;">
              {% for oposicion in all_oposicion %}
              <optgroup label="{{oposicion.NomOposicion}}">
                {% for id, NomTemario, IdOposicion in all_temario %}
                  {% if IdOposicion == oposicion.id %}
                    <option value="{{ id }}" name="temarios">{{ NomTemario }}</option>
                  {% endif %}
                {% endfor %}
            </optgroup>
              {% endfor %}
            </select>
          </div>
          <div class="mb-3">
            <div class="mb-3">
              <label for="id_NumPreguntas" class="form-label">Número de preguntas
                <p id="numero">18</p>
              </label>
              <input type="range" class="form-range" min="5" max="30" name="NumPreguntas" required="" aria-invalid="true" id="id_NumPreguntas">
            </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="reset" class="botonCancelar" id="botonCancelar" data-bs-dismiss="modal">CANCELAR</button>
        <button type="submit" class="botonTemario" id="botonAñadir" name="añadirTemario">AÑADIR</button>
        <div id="spinner" class="spinner-border text-info d-none" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <div id="spinnerText" class="d-none">
          Creando prueba con IA, esto puede tardar unos minutos, no actualice la página.
        </div>
      </div>
    </form>
    </div>
  </div>
</div>
</div>

<script>
let barraDeTiempo = document.getElementById('id_NumPreguntas');
let cajaNumeral = document.getElementById('numero');
// Asignar evento a barra
barraDeTiempo.addEventListener('input', mostrar);
// Función para actualizar
function mostrar() {
    // Asignar a caja el valor de la barra
    cajaNumeral.innerHTML = barraDeTiempo.value;
}
</script>
<script>
  document.addEventListener("DOMContentLoaded", function() {
      const form = document.getElementById('formtemario');
      const spinner = document.getElementById('spinner');
        const spinnerText = document.getElementById('spinnerText');
      const botonCancelar = document.getElementById('botonCancelar');
      const botonAñadir = document.getElementById('botonAñadir');

      form.addEventListener('submit', function() {
          // Ocultar botones y mostrar spinner
          botonCancelar.style.display = 'none';
          botonAñadir.style.display = 'none';
          spinner.classList.remove('d-none');
          spinnerText.classList.remove('d-none');
      });
  });
</script>
{% endblock section2 %}